server:
  port: 8080

spring:
  application:
    name: api-gateway

cloud:
  gateway:
    routes:
      ##authservice
      - id: authenBizmatch
        uri: lb://authenBizmatch
        predicates:
          -Path=/auth/**
        filtres:
          -StripPrefix=1
      ##authservice
      - id: registerMicroservice
        uri: lb://registerMicroservice
        predicates:
          -Path=/register/**
        filtres:
          -StripPrefix=1
          
          
          ##PlanStrategique
            - id: planStrategiqueMicroservice
            uri: lb://planStrategiqueMicroservice
            predicates:
              -Path=/register/**
            filtres:
              -StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka